name: Pryzma Action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Python Setup (jer koristimo python za ovo)
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: AI analiza
      env:
        CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
      run: |
        python main.py

    - name: upload results (json output od ai analize)
      uses: actions/upload-artifact@v4
      with:
        name: analysis-results
        path: results/
