name: Pryzma CI

on:
  workflow_call:

jobs:
  get-paths:
    runs-on: ubuntu-latest
    outputs:
      file_paths: ${{ steps.find-paths.outputs.paths }}
    steps:
    - uses: actions/checkout@v4

    - name: Find paths
      id: find-paths
      run: |
        paths=$(find . \
          -not \( -path './__tests__/*' -prune \) \
          -not \( -path './node_modules/*' -prune \) \
          -not \( -path './.git/*' -prune \) \
          -type f \
          -not \( -name '*.png' -o -name '*.jpg' -o -name '*.json' -o -name '*.md' \) \
          -print)
        echo "paths<<EOF" >> $GITHUB_OUTPUT
        echo "$paths">> $GITHUB_OUTPUT
        echo "EOF" >>$GITHUB_OUTPUT
